export const ADD_COUNTRY_LIST = 'ADD_COUNTRY_LIST';
export const ADD_COUNTRY_DEPART = 'ADD_COUNTRY_DEPART';
export const ADD_COUNTRY_ARRIVE = 'ADD_COUNTRY_ARRIVE';
export const ADD_ARRIVE_ALPHA_2 = 'ADD_ARRIVE_ALPHA_2';
export const ADD_DEPART_ALPHA_2 = 'ADD_DEPART_ALPHA_2';
export const ADD_TEXT = 'ADD_TEXT';
